<a href="https://colab.research.google.com/github/updalla-apshir/machine-learning-projects/blob/main/5_3_Model_Selection_in_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_openml

In [ ]:
# importing the models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

We will be working on the Heart Disease dataset

In [ ]:
# loading the data to a Pandas DataFrame
heart = fetch_openml(name='heart', version=1)

heart_data = pd.DataFrame(
    heart.data.toarray(),
    columns=heart.feature_names
)

heart_data['target'] = heart.target

In [ ]:
# print first 5 rows of the dataset
heart_data.head()

,att_1,att_2,att_3,att_4,att_5,att_6,att_7,att_8,att_9,att_10,att_11,att_12,att_13,target
0,0.708333,1.0,1.000000,-0.320755,-0.105023,-1.0,1.0,-0.419847,-1.0,-0.225806,0.0,1.000000,-1.0,1.0
1,0.583333,-1.0,0.333333,-0.603774,1.000000,-1.0,1.0,0.358779,-1.0,-0.483871,0.0,-1.000000,1.0,-1.0
2,0.166667,1.0,-0.333333,-0.433962,-0.383562,-1.0,-1.0,0.068702,-1.0,-0.903226,-1.0,-1.000000,1.0,1.0
3,0.458333,1.0,1.000000,-0.358491,-0.374429,-1.0,-1.0,-0.480916,1.0,-0.935484,0.0,-0.333333,1.0,-1.0
4,0.875000,-1.0,-0.333333,-0.509434,-0.347032,-1.0,1.0,-0.236641,1.0,-0.935484,-1.0,-0.333333,-1.0,-1.0

In [ ]:
# number of rows and columns in the dataset
heart_data.shape

(270, 14)

In [ ]:
# checking for missing values
heart_data.isnull().sum()

att_1     0
att_2     0
att_3     0
att_4     0
att_5     0
att_6     0
att_7     0
att_8     0
att_9     0
att_10    0
att_11    0
att_12    0
att_13    0
target    0
dtype: int64

In [ ]:
# checking the distribution of Target Variable
heart_data['target'].value_counts()

target
-1.0    150
 1.0    120
Name: count, dtype: int64

Splitting the Features and Target

In [ ]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

**Model Selection**

1. Comparing the models with default hyperparameter values using Cross Validation

In [ ]:
models = [LogisticRegression(), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [ ]:
def compare_models_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, X, Y, cv=5)

    average_accuracy = cv_score.mean()
    average_accuracy = average_accuracy * 100
    average_accuracy = round(average_accuracy,2)

    print('cross validation accuracies for the ', model, ' = ', cv_score)
    print('aacuracy score of ', model, ' = ', average_accuracy, '%')
    print('--------------------------------------------------')

In [ ]:
compare_models_cross_validation()

cross validation accuracies for the  LogisticRegression()  =  [0.7962963  0.81481481 0.90740741 0.81481481 0.87037037]
aacuracy score of  LogisticRegression()  =  84.07 %
--------------------------------------------------
cross validation accuracies for the  SVC(kernel='linear')  =  [0.7962963  0.83333333 0.88888889 0.83333333 0.83333333]
aacuracy score of  SVC(kernel='linear')  =  83.7 %
--------------------------------------------------
cross validation accuracies for the  KNeighborsClassifier()  =  [0.75925926 0.87037037 0.83333333 0.81481481 0.7962963 ]
aacuracy score of  KNeighborsClassifier()  =  81.48 %
--------------------------------------------------
cross validation accuracies for the  RandomForestClassifier()  =  [0.7037037  0.7962963  0.87037037 0.83333333 0.88888889]
aacuracy score of  RandomForestClassifier()  =  81.85 %
--------------------------------------------------

2. Comparing the models with different Hyperparameter values using GridSearchCV

In [ ]:
models = [LogisticRegression(), SVC(), KNeighborsClassifier(), RandomForestClassifier()]

In [ ]:
# creating a dictionary that contains hyperparameter values for the above mentioned models


model_hyperparameters = {


    'log_reg_hyperparameters': {

        'C' : [1,5,10,20]
    },

    'svc_hyperparameters': {

        'kernel' : ['linear','poly','rbf','sigmoid'],
        'C' : [1,5,10,20]
    },


    'KNN_hyperparameters' : {

        'n_neighbors' : [3,5,10]
    },


    'random_forest_hyperparameters' : {

        'n_estimators' : [10, 20, 50, 100]
    }
}

In [ ]:
type(model_hyperparameters)

dict

In [ ]:
model_hyperparameters.keys()

dict_keys(['log_reg_hyperparameters', 'svc_hyperparameters', 'KNN_hyperparameters', 'random_forest_hyperparameters'])

In [ ]:
model_hyperparameters.values()

dict_values([{'C': [1, 5, 10, 20]}, {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}, {'n_neighbors': [3, 5, 10]}, {'n_estimators': [10, 20, 50, 100]}])

In [ ]:
model_keys = list(model_hyperparameters.keys())

In [ ]:
model_hyperparameters['log_reg_hyperparameters']

{'C': [1, 5, 10, 20]}

Applying GridSearchCV

In [ ]:
def modelSelection(models, hyperparameters):

  result = []
  i = 0

  for model in models:

    key = model_keys[i]
    params = hyperparameters[key]

    i +=1
    print(model)
    print(params)

    classifier = GridSearchCV(model, params,cv=5)
    classifier.fit(X,Y)

    result.append({
        'model used' : model,
        'highest score' : classifier.best_score_,
        'best hyperparameters' : classifier.best_params_

    })

    result_dataframe = pd.DataFrame(result, columns=['model used','highest score','best hyperparameters'])

  return result_dataframe

In [ ]:
modelSelection(models,model_hyperparameters)

LogisticRegression()
{'C': [1, 5, 10, 20]}
SVC()
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
RandomForestClassifier()
{'n_estimators': [10, 20, 50, 100]}

                 model used  highest score          best hyperparameters
0      LogisticRegression()       0.840741                      {'C': 1}
1                     SVC()       0.837037  {'C': 1, 'kernel': 'linear'}
2    KNeighborsClassifier()       0.814815            {'n_neighbors': 5}
3  RandomForestClassifier()       0.825926          {'n_estimators': 50}